--ZADANIE 1
CREATE TABLE MIASTO(
ID_MIASTA INTEGER NOT NULL,
NAZWA VARCHAR2(50) NOT NULL,
PRIMARY KEY (ID_MIASTA));
--ZADANIE 2
CREATE TABLE OSOBA(
ID_OSOBY INTEGER PRIMARY KEY,
NAZWISKO VARCHAR2(50) NOT NULL,
DATA_URODZENIA DATE NULL,
ADRES VARCHAR2(100) NULL,
ID_MIASTO INTEGER NOT NULL,
FOREIGN KEY (ID_MIASTO)REFERENCES MIASTO);
--ZADANIE 3
ALTER TABLE OSOBA ADD (ZAWOD VARCHAR2(20) NULL);
--ZADANIE 4
INSERT INTO MIASTO(ID_MIASTA, NAZWA) VALUES (1,'Warszawa');
INSERT INTO MIASTO(ID_MIASTA, NAZWA) VALUES (2,'Krakow');
INSERT INTO MIASTO(ID_MIASTA, NAZWA) VALUES (3,'Gdansk');
--ZADANIE 5
INSERT INTO OSOBA(ID_OSOBY, NAZWISKO, DATA_URODZENIA, ADRES, ID_MIASTO)
VALUES (1,'SERAFINSKI',TO_DATE('1999-05-30','YYYY-MM-DD'),'WAWER',1);
INSERT INTO OSOBA(ID_OSOBY, NAZWISKO, DATA_URODZENIA, ADRES, ID_MIASTO)
VALUES (2,'KOLPAK',TO_DATE('1999-04-01','YYYY-MM-DD'),'URSYNOW',3);
INSERT INTO OSOBA(ID_OSOBY, NAZWISKO, DATA_URODZENIA, ADRES, ID_MIASTO)
VALUES (3,'KOWALSKI',TO_DATE('1999-07-17','YYYY-MM-DD'),'RAKOWIEC',2);
--ZADANIE 6
INSERT INTO OSOBA(ID_OSOBY, NAZWISKO, DATA_URODZENIA, ADRES, ID_MIASTO)
SELECT EMPNO,ENAME,NULL,NULL,3 FROM EMP;
--ZADANIE 7
UPDATE OSOBA
SET DATA_URODZENIA = TO_DATE('1999-09-22','YYYY-MM-DD'),
ADRES = 'OCHOTA'
WHERE ID_OSOBY = 1;
--ZADANIE 8
DELETE FROM OSOBA
WHERE NAZWISKO LIKE 'P%';
--ZADANIE 9
ALTER TABLE OSOBA ADD(PESEL VARCHAR2(11) UNIQUE);
--ZADANIE 10
ALTER TABLE OSOBA ADD (CHECK (DATA_URODZENIA<=TO_DATE('1900-01-01','YYYY-MM-DD')));
INSERT INTO OSOBA(ID_OSOBY, NAZWISKO, DATA_URODZENIA, ADRES, ID_MIASTO)
VALUES (0,'NOWAK',TO_DATE('1899-05-30','YYYY-MM-DD'),'WAWER',3);
--ZADANIE 11
DROP TABLE OSOBA;
DROP TABLE MIASTO;