-- ZADANIE 1
SELECT ROUND(AVG(SAL), 2) "SREDNIA PENSJA"
FROM EMP;
-- ZADANIE 2
SELECT MIN(SAL) "MINIMALNA PENSJA"
FROM EMP
WHERE JOB = 'CLERK';
-- ZADANIE 3
SELECT COUNT(DEPTNO) "ILE PRACOWNIKOW W DEPT 20"
FROM EMP
WHERE DEPTNO = 20;
-- ZADANIE 4
SELECT JOB, ROUND(AVG(SAL),2) "SREDNIA PENSJA"
FROM EMP
GROUP BY JOB;
-- ZADANIE 5
SELECT JOB, ROUND(AVG(SAL),2) "SREDNIA PENSJA"
FROM EMP
WHERE NOT JOB = 'MANAGER'
GROUP BY JOB;
-- ZADANIE 6
SELECT JOB, DEPTNO, ROUND(AVG(SAL),2) "SREDNIA PENSJA"
FROM EMP
GROUP BY JOB, DEPTNO;
-- ZADANIE 7
SELECT JOB, MAX(SAL) "MINIMALNA PENSJA"
FROM EMP
GROUP BY JOB;
-- ZADANIE 8
SELECT DEPTNO, ROUND(AVG(SAL),2) "SREDNIA PENSJA"
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*) > 3;
-- ZADANIE 9
SELECT JOB, ROUND(AVG(SAL),2) "SREDNIA PENSJA"
FROM EMP
GROUP BY JOB
HAVING ROUND(AVG(SAL),2) >= 3000;
-- ZADANIE 10
SELECT JOB, ROUND(AVG(SAL),2) "SREDNIA PENSJA", ROUND(AVG(12*SAL+NVL(COMM,0)),2) "ŚREDNIA ROCZNA PENSJA"
FROM EMP
GROUP BY JOB;
-- ZADANIE 11
SELECT MAX(SAL)-MIN(SAL) "ROZNICA MAX-MIN"
FROM EMP;
-- ZADANIE 12
SELECT DEPTNO, COUNT(*)
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*)>3;
-- ZADANIE 13
SELECT ROUND(MAX(COUNT(*)))  "LICZBA PRACOWNIKOW"
FROM EMP
GROUP BY EMPNO;
-- Aby sprawdzić, czy numery empno są rzeczywiście wzajemnie różne,
-- grupujemy po nich i liczymy ile jest rekordów w każdej grupie.
-- Następnie bierzemy maksimum z tych numerów.
-- Jeżeli jest 1 to ok., jeżeli np. 2 to znaczy, że istnieje 2 pracowników o
-- takim samym numerze.

-- ZADANIE 14
SELECT MGR "MANAGER", MIN(SAL) AS NAJNIZSZA
FROM EMP
GROUP BY MGR
HAVING MIN(SAL) > 1000
ORDER BY NAJNIZSZA;
-- ZADANIE 15
SELECT COUNT(*) "LICZBA PRACOWNIKOW"
FROM EMP, DEPT
WHERE LOC = 'DALLAS' AND EMP.DEPTNO = DEPT.DEPTNO;
-- ZADANIE 16
SELECT GRADE "KLASA", MAX(SAL) "MAX PENSJA"
FROM EMP, SALGRADE
WHERE SAL BETWEEN LOSAL AND HISAL
GROUP BY GRADE;
-- ZADANIE 17
SELECT SAL "PENSJA", COUNT(*) "ILOSC"
FROM EMP
GROUP BY SAL
HAVING COUNT(*)>1;
-- ZADANIE 18
SELECT ROUND(AVG(SAL)) "SREDNIA 2 KLASA"
FROM EMP, SALGRADE
WHERE GRADE = 2 AND SAL BETWEEN LOSAL AND HISAL;
-- ZADANIE 19
SELECT MGR "MANAGER", COUNT(*) "ILOSC PRACOWNIKOW"
FROM EMP
GROUP BY MGR;
-- ZADANIE 20
SELECT SUM(SAL) "SUMA KLASY 1"
FROM EMP, SALGRADE
WHERE SAL BETWEEN LOSAL AND HISAL AND GRADE = 1;