-- ZADANIE 1
SELECT DEPTNO, ENAME,EMPNO FROM EMP;
-- ZADANIE 2
SELECT * FROM EMP;
-- ZADANIE 3
SELECT ENAME, 12*SAL FROM EMP;
-- ZADANIE 4
SELECT ENAME, (12*SAL)+250 FROM EMP;
-- ZADANIE 5
SELECT ENAME, 12*SAL "ROCZNA" FROM EMP;
-- ZADANIE 6
SELECT ENAME, 12*SAL "R PENSJA" FROM EMP;
-- ZADANIE 7
SELECT EMPNO || ENAME "EMPLOYEE" FROM EMP;
-- ZADANIE 8
SELECT ENAME || ' pracuje w dziale ' || DEPTNO FROM EMP;
-- ZADANIE 9
SELECT ENAME, 12*(SAL)+NVL(COMM,0) AS "ROCZNA Z PROWIZJA" FROM EMP;
-- ZADANIE 10
SELECT DEPTNO FROM DEPT;
-- ZADANIE 11
SELECT DISTINCT DEPTNO FROM EMP;
-- ZADANIE 12
SELECT DISTINCT DEPTNO, JOB FROM EMP;
-- ZADANIE 13
SELECT * FROM EMP ORDER BY ENAME;
-- ZADANIE 14
SELECT * FROM EMP ORDER BY HIREDATE DESC;
-- ZADANIE 15
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO FROM EMP ORDER BY DEPTNO ASC, 6 DESC;
/* Tutaj można bylo by nie pisać tego ASC -> bo normalnie jest rosnąco! */
-- ZADANIE 16
SELECT ENAME, EMPNO, JOB, DEPTNO FROM EMP WHERE JOB = 'CLERK';
-- ZADANIE 17
SELECT DNAME, DEPTNO FROM DEPT WHERE DEPT.DEPTNO > 20;
-- ZADANIE 18
SELECT ENAME, COMM, SAL FROM EMP WHERE COMM > SAL;
-- ZADANIE 19
SELECT * FROM EMP WHERE SAL BETWEEN 1000 AND 2000;
-- ZADANIE 20
SELECT * FROM EMP WHERE MGR = 7902 OR MGR = 7566 OR MGR = 7788;
-- ZADANIE 21
SELECT * FROM EMP WHERE ENAME LIKE 'S%';
-- ZADANIE 22
SELECT * FROM EMP WHERE ENAME LIKE '____';
-- ZADANIE 23
SELECT * FROM EMP WHERE MGR IS NULL;
-- ZADANIE 24
SELECT * FROM EMP WHERE NOT SAL >=1000 OR NOT SAL<=2000;
-- ZADANIE 25
SELECT * FROM EMP WHERE ENAME NOT LIKE 'M%';
-- ZADANIE 26
SELECT * FROM EMP WHERE MGR IS NOT NULL;
-- ZADANIE 27
SELECT * FROM EMP WHERE JOB = 'CLERK' AND SAL >= 1000 AND SAL <2000;
-- ZADANIE 28
SELECT * FROM EMP WHERE JOB = 'CLERK' OR SAL >= 1000 AND SAL <2000;
-- ZADANIE 29
SELECT * FROM EMP WHERE JOB = 'MANAGER' AND SAL > 1500 OR JOB = 'SALESMAN';
-- ZADANIE 30
SELECT * FROM EMP WHERE JOB = 'MANAGER' AND SAL > 1500 OR JOB = 'SALESMAN' AND SAL > 1500;
-- ZADANIE 31
SELECT * FROM EMP WHERE JOB = 'MANAGER' OR JOB = 'CLERK' AND DEPTNO = 10;
-- ZADANIE 32
SELECT * FROM SALGRADE;
-- ZADANIE 33
SELECT * FROM DEPT;
-- ZADANIE 34
SELECT DEPTNO, DNAME FROM DEPT ORDER BY DEPTNO;
-- ZADANIE 35
SELECT DISTINCT JOB FROM EMP;
-- ZADANIE 36
SELECT * FROM EMP WHERE DEPTNO = 10 OR DEPTNO = 20 ORDER BY ENAME;
-- ZADANIE 37
SELECT * FROM EMP WHERE ENAME LIKE '%TH%' OR ENAME LIKE '%LL%';
-- ZADANIE 38
SELECT ENAME, DEPTNO, HIREDATE FROM EMP WHERE EXTRACT(YEAR FROM HIREDATE) = 1980;
-- ZADANIE 39
SELECT ENAME, 12*EMP.SAL "ROCZNA", COMM FROM EMP WHERE SAL>COMM ORDER BY SAL DESC, ENAME;