--1
SELECT PACJENT.IMIE "ImiePacjent", PACJENT.NAZWISKO "NazwiskoPacjent", SUM(CENA) "SumaKosztow"FROM PACJENT
JOIN WIZYTY ON PACJENT.IDPACJENTA = WIZYTY.IDPACJENTA
JOIN LEKARZ ON WIZYTY.IDLEKARZA = LEKARZ.IDLEKARZA
WHERE SPECJALIZACJA = 'Internista' AND EXTRACT(YEAR FROM DATA) = 2013
GROUP BY PACJENT.IMIE, PACJENT.NAZWISKO;
--2
SELECT IMIE "ImieLekarz", NAZWISKO "NazwiskoLekarz", MAX(CENA) "NajdroszaWizyta" FROM LEKARZ
JOIN WIZYTY ON LEKARZ.IDLEKARZA = WIZYTY.IDLEKARZA
GROUP BY IMIE, NAZWISKO
HAVING COUNT(*)>=2;
--3
SELECT LEKARZ.IMIE "ImieLekarz" ,  LEKARZ.NAZWISKO "NazwiskoLekarz" FROM LEKARZ
JOIN WIZYTY ON LEKARZ.IDLEKARZA = WIZYTY.IDLEKARZA
JOIN PACJENT ON WIZYTY.IDPACJENTA = PACJENT.IDPACJENTA
WHERE PACJENT.IMIE = 'Jan' AND PACJENT.NAZWISKO = 'Kowalski';
--4
SELECT IMIE "ImiePacjent", NAZWISKO "NazwiskoPacjent", MIN (DATA) "DataWizyty" FROM PACJENT
JOIN WIZYTY ON PACJENT.IDPACJENTA = WIZYTY.IDPACJENTA
GROUP BY IMIE, NAZWISKO;
--5 - NIE SKONCZONE
SELECT SPECJALIZACJA "Specjalizacja", COUNT(*) "LiczbaWizyt" FROM LEKARZ
JOIN WIZYTY ON LEKARZ.IDLEKARZA = WIZYTY.IDLEKARZA
GROUP BY SPECJALIZACJA;
--6 - NIE SKONCZONE
SELECT NVL(SPECJALIZACJA,'Brak') "Specjalizacja",SUM(CENA) "SumaOplat" FROM LEKARZ
JOIN WIZYTY on LEKARZ.IDLEKARZA = WIZYTY.IDLEKARZA
GROUP BY SPECJALIZACJA;
--7
SELECT IMIE || ' ' || NAZWISKO "LEKARZ" FROM LEKARZ
WHERE SPECJALIZACJA LIKE 'Z%' AND PENSJA < 3000
ORDER BY SPECJALIZACJA DESC, NAZWISKO ASC;
--8 -- NIE SKONCZONE
SELECT PACJENT.NAZWISKO "NazwiskoPacjent", LEKARZ.NAZWISKO "NazwiskoLekarz", DATA "DataWizyty", CENA "KosztWizyty"
FROM LEKARZ
JOIN WIZYTY ON LEKARZ.IDLEKARZA = WIZYTY.IDLEKARZA
JOIN PACJENT ON WIZYTY.IDPACJENTA = PACJENT.IDPACJENTA;
--9 - NIE SKONCZONE
SELECT IMIE "ImieLekarz", NAZWISKO "NazwiskoLekarz", AVG(CENA) "SredniaCena" FROM LEKARZ
JOIN WIZYTY ON LEKARZ.IDLEKARZA = WIZYTY.IDLEKARZA
GROUP BY IMIE, NAZWISKO;
--10
SELECT SPECJALIZACJA "Specjalizacja", AVG(CENA) "SredniaCena", COUNT(*) "LiczbaWizyt" FROM LEKARZ
JOIN WIZYTY ON LEKARZ.IDLEKARZA = WIZYTY.IDLEKARZA
 WHERE SPECJALIZACJA NOT IN (SELECT SPECJALIZACJA FROM LEKARZ WHERE SPECJALIZACJA = 'Dentysta')
GROUP BY SPECJALIZACJA;
--11
DELETE FROM LEKARZ
WHERE SPECJALIZACJA LIKE 'A%';
--12

--13
SELECT * FROM LEKARZ
JOIN WIZYTY ON LEKARZ.IDLEKARZA = WIZYTY.IDLEKARZA
WHERE DATA NOT IN (SELECT DATA FROM WIZYTY WHERE EXTRACT(YEAR FROM DATA) = 2008);
--14
